### ISSUE TITLE
Publish to app store

### ISSUE THREAD

**Issue by wassaparala** [jeffkreeftmeijer/UitzendingGemist#12]
Why could this not be in the app store

**Comment by crxdelsol** [comment]
It could be if the name would be changed to something else.

**Comment by amphorainteractive** [comment]
It's a public available API so as long as you don't use a trademarked name or icon it should be fine I guess.

**Comment by crxdelsol** [comment]
Same thing I thought. Only make sure you don’t claim their name just in case they want to use their service in one app too.
However, since you need to host your own server for this, it is not App Store capable. In that case, you need a single client app.

**Comment by kjwierenga** [comment]
What do you mean by "you need to host your own server for this, it is not App Store capable"? Maybe Apple would not allow the use of the TVBaseURL (http://atvnpo.s3-website-us-east-1.amazonaws.com/)? That could be hosted on a dedicated domain (e.g. atvnpo.nl).

**Comment by crxdelsol** [comment]
Why would you want an external server to be used for stuff like this while the Apple TV has more then enough power to handle this on its own. Why not doing this natively within one app bundle.

**Comment by amphorainteractive** [comment]
because then you need to sideload the new app everytime there is a small update.
if it would be available in the app store it wouldn’t be a good idea, i think apple even denies apps that load code remotely.

**Comment by crxdelsol** [comment]
Apple does not deny that. It's just an ugly approach.
That's the 'server-client'-setup which is supported by the Apple TV. Also because this reduces disk usage. But I dislike that approach, lots of examples online using TVJS/TVML use server-client setups.

**Comment by amphorainteractive** [comment]
You are allowed to load images/video's/other resources remotely off course. But not actual code. Because it would allow you to change functionality after the app is approved and violate app store regulations.

**Comment by wassaparala** [comment]
But TVML is invented for this right?
So you can change things remotely.

**Comment by amphorainteractive** [comment]
Quote:
3.3.2 An Application may not download or install executable code. Interpreted code may only be used in an Application if all scripts, code and interpreters are packaged in the Application and not downloaded. The only exception to the foregoing is scripts and code downloaded and run by Apple's built-in WebKit framework, provided that such scripts and code do not change the primary purpose of the Application by providing features or functionality that are inconsistent with the intended and advertised purpose of the Application as submitted to the App Store.

**Comment by crxdelsol** [comment]
That's more the native compiled code of the application. You are allowed to setup a TVJS server, to communicate with your TVML client. That's the whole purpose of these separate solutions.
You are not allowed to put some backdoor stuff in your main (client) application you could use to change the client application on the Apple TV directly. Server side you cannot do much.

**Comment by jeffkreeftmeijer** [comment]
Hey there, thanks for discussing this. I've tried to explain why I'm not releasing this project to the App Store in #22.
