### ISSUE TITLE
Add digital stream to the app

### ISSUE THREAD

**Issue by iAmRenzo** [jeffkreeftmeijer/UitzendingGemist#16]
The NPO has three things: live, digital themed channels and live tv. This first is covered, the last has an issue but there is still the digital channels, like Cultura, 101, NPO Politiek.

To make a killer NPO app that digital streams should be added. Or in a seperate view or in the same view as the live streams of NPO1,2,3...

**Comment by michaeldam** [comment]
+1. Adding those streams will make it an NPO killer app for sure.

**Comment by jeffkreeftmeijer** [comment]
Thanks for opening this issue! However, like #9, I think this is a better fit for @Mauricevb's NPO Live app (https://github.com/Mauricevb/NPO-Live-Apple-TV-4). Could you check out if NPO-Live already supports this? If not, please open an issue there.
