### ISSUE TITLE
Issue when running the application

### ISSUE THREAD

**Issue by vanbemmel** [jeffkreeftmeijer/UitzendingGemist#18]
When I run the application in Xcode I get this message:
An App ID with Identifier 'com.jeffkreeftmeijer.UitzendingGemist' is not available. Please enter a different string.

I was logged in with my own Apple developer ID.

**Comment by iAmRenzo** [comment]
You need to make the identifier unique. So add your own string like 'com.vanbemmel.jeffkreeftmeijer.UitzendingGemist' and it will work.
I will add better installation instructions to the readme tonight.

**Comment by jeffkreeftmeijer** [comment]
Thanks for helping out @iAmRenzo!

@vanbemmel did you get it to work? 

I'm closing this for now. If anyone has any more questions about this, please don't hesitate to reopen this issue.
