### ISSUE TITLE
Updating and version history

### ISSUE THREAD

**Issue by bluevoice** [jeffkreeftmeijer/UitzendingGemist#19]
Hi,

First of all, congratulations with this app, it it fantastic. As I am kind of novice to installation / app developing I have the following 2 questions:
1) what is the best way to update the app? Delete it from Apple TV, download new version from GitHub and reinstall or is there a better way?
2) Related to 1) Where can I see the current version of the app on my Apple TV so that I can compare it with the (latest) version of the app available on GitHub?

Your feedback will be highly appreciated!

**Comment by jeffkreeftmeijer** [comment]
Hey @bluevoice,

We might need a clearer explanation of this in the `README.md`, but most of the time, you shouldn't have to update the app at all, as the TVML views and the javascript is hosted on S3 (http://atvnpo.s3-website-us-east-1.amazonaws.com), and updated whenever something changes in the code base. Your Apple TV will use the online versions of these files, so you're always up to date.

If there's an update that requires you to update the app itself, `git pull` the changes (https://help.github.com/articles/fetching-a-remote/#pull), build and run, and the updated app should run on your device.

**Comment by bluevoice** [comment]
Thanks, I did read the realm file but even now it's unclear to me in what cases I need to completely reinstall te app and when not. For instance, do I need to reinstall the app to see the new icon? Same for the live channels, I don't see those in my app.

**Comment by jeffkreeftmeijer** [comment]
You'd have to update the app to get the icon, as the icon was added to the application bundle. We're still working on the live channels in #15, so that's not merged in yet. However, when that's done, you'll automatically get the live channels without updating, as that's a feature in `/client`.

**Comment by jeffkreeftmeijer** [comment]
Closing this. If anyone has any more questions about this, please don't hesitate to reopen this issue.
