### ISSUE TITLE
Issues with the (broadcast)dates within the app

### ISSUE THREAD

**Issue by iAmRenzo** [jeffkreeftmeijer/UitzendingGemist#23]
There was a request to add dates of broadcast to the stream, they are added and the issue was closed but it seems there is something wrong with them.

First
![img_1953](https://cloud.githubusercontent.com/assets/1183790/11178634/47334178-8c4e-11e5-98f1-1da5d74d9c94.JPG)
Look at the dates below the thumbnails (they are ltr: 13-10, 06/10, 30/9, 23/9 amd 16/9).
Now look at the dates from NPO.nl, check the corresponding thumbnails.
![webcheck](https://cloud.githubusercontent.com/assets/1183790/11178689/ab0f3238-8c4e-11e5-8063-d0e142d39232.jpg)
It seems the have the wrong month.

**Comment by jeffkreeftmeijer** [comment]
Hey Renzo,

Thanks for letting me know! Could you create two issues for this (one for
the wrong dates and one for the "missing" ones), to keep the conversation
public and allowing others to look into this?

Thanks again!

-- Jeff

**Comment by jeffkreeftmeijer** [comment]
Hey @iAmRenzo, 

Thanks for reporting this issue, great catch! This seems to be a off-by-one error, as `Date.getMonth()` is zero-based. 

I've opened #24 for the other issue, so we can close this one when it's fixed without having to wait for the other issue to be resolved too.

**Comment by amphorainteractive** [comment]
Totally agree! I hate sites/apps using dates without day of the week. Even better would be to omit year when it's not older than 11 months or maybe even 'last Friday 20:25". Some frameworks have a function for that. Dunno about ios

**Comment by jeffkreeftmeijer** [comment]
@bluevoice @amphorainteractive yes, that'd be possible. We'd be able to use the `getDay()` function on date and keep a list of weekdays in Dutch. While we're at it, we could also add month names. Could you open a new issue (or a pull request) for this, @bluevoice?

**Comment by bluevoice** [comment]
Done, see https://github.com/jeffkreeftmeijer/UitzendingGemist/issues/25
