### ISSUE TITLE
Legacy Swift (tvOS10)

### ISSUE THREAD

**Issue by 41114** [jeffkreeftmeijer/UitzendingGemist#31]
Hello, Stumbled upon this gem of an app when I get it to work.

When hitting play I get the following message:
"Use Legacy Swift Language Version" (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly. 

When I try to convert to a newer (2.3 or 3.0) version of Swift Xcode fails with showing:
Could not find test host for UitzendingGemistTests: TEST_HOST evaluates to "/Users/username/Library/Developer/Xcode/DerivedData/UitzendingGemist-fptgsewgbfaxshbvzeulnnefdfio/Build/Products/Debug-appletvos/UitzendingGemist.app/UitzendingGemist"

**Comment by Raezor87** [comment]
Hi,

i have the same problem as 41114.
(Running Xcode Version 8.0 (8A218a))

**Comment by jeffkreeftmeijer** [comment]
I've locked the Swift version to 2.3 and the tvOS deployment target to 9.0 in ae8d94afa67716f09b50b3e3592db54c0d4fcc46. Could you pull those changes and try again?

**Comment by Raezor87** [comment]
The changes made it work, thnx

**Comment by Wildeweg** [comment]
Still not working for me. Runningn Xcode Version 8.3.3
