### ISSUE TITLE
swift-probleem

### ISSUE THREAD

**Issue by tomvanhelderen** [jeffkreeftmeijer/UitzendingGemist#32]
Met de updates van de laatste tijd, is er een swift-probleem, waardoor de app niet meer werkt of opnieuw gebouwd kan worden...
![schermafbeelding 2016-09-19 om 21 12 19](https://cloud.githubusercontent.com/assets/22304029/18645516/c6bc27be-7ead-11e6-965d-9954c81c9a69.png)
Enig idee voor een oplossing?

**Comment by jeffkreeftmeijer** [comment]
Yo Tom,

Xcode doet suggesties als je op de bolletjes in de zijbalk klikt. Kun je dat eens proberen om te kijken of de build dan wel weer werkt? Als het werkt is een pull request welkom. :)

**Comment by tomvanhelderen** [comment]
Dag Jeff,
Ik kom er met de Swift-converter niet verder mee...
Het gekke is dat bij je collega van de NPO-live-app er geen problemen zijn...
Wat te doen?
![schermafbeelding 2016-09-20 om 20 02 38](https://cloud.githubusercontent.com/assets/22304029/18682682/7c9e948a-7f6d-11e6-9727-8666c4029c56.png)

**Comment by tomvanhelderen** [comment]
En als ik de swift wil converten krijg ik deze melding. Misschien kom je er verder mee?
![schermafbeelding 2016-09-20 om 20 29 56](https://cloud.githubusercontent.com/assets/22304029/18683588/1de9c514-7f71-11e6-85ae-2b4709ed87ce.png)
