### ISSUE TITLE
UitzendingGemist for ATV3 on IOS 7.2.2

### ISSUE THREAD

**Issue by MRRMV** [jeffkreeftmeijer/UitzendingGemist#38]
I have an ATV3 on IOS 7.2.2. and I want to install UitzendingGemist  but the latest version does not work since this is for IOS 9, is there an older version available somewhere that I can use?

**Comment by nickdekruijk** [comment]
There is no version that will work on ATV3

**Comment by MRRMV** [comment]
Too bad😤  Thanks for the quick reply.
