### ISSUE TITLE
Find a fallback image for episodes without images

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [jeffkreeftmeijer/UitzendingGemist#4]

**Comment by FrnklyN** [comment]
What are the dimensions for this image?

**Comment by iAmRenzo** [comment]
You also could make a grayscale image of the logo of the app as a fallback. Doesn't attract much attention and looks good, I think.

**Comment by jeffkreeftmeijer** [comment]
Since 2e4a69643af762c141e06fc208e728bb11cccfca, the episode thumbnails and backgrounds show static when no image can be found. It would have been awesome, but I couldn't het the animated GIF to animate.

![simulator screen shot 15 nov 2015 19 11 26](https://cloud.githubusercontent.com/assets/43621/11170558/2753f4cc-8bd8-11e5-8dcc-5e2512e1376c.png)

I'm still open for better ideas (or a way to get the GIF to animate), but I'm closing this for now. Please reopen this issue if you have anything to add.
