### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [jeffkreeftmeijer/UitzendingGemist#5]
https://developer.apple.com/tvos/human-interface-guidelines/icons-and-images/
https://upload.wikimedia.org/wikipedia/commons/7/78/Uitzending_Gemist_Logo.svg

The icon should probably look somewhat like this: https://github.com/alloy/UitzendingGemist-ATV2/blob/master/Resources/AppIcon.png.

Any help would be appreciated.

**Comment by FrnklyN** [comment]
I've made an app icon that must look great. I'm looking into making a top shelf image.

![front](https://cloud.githubusercontent.com/assets/15732484/11037880/7b677be2-8700-11e5-8091-653a3b529de5.png)
![middle](https://cloud.githubusercontent.com/assets/15732484/11037881/7b6b09ec-8700-11e5-91c8-76cada369e9e.png)
![back](https://cloud.githubusercontent.com/assets/15732484/11037882/7b6f322e-8700-11e5-840a-f700e71eab00.png)

**Comment by basvroegop** [comment]
Would it actually be possible to show either most viewed or recent shows in the Top Shelf, the way Netflix and Plex show content?

**Comment by jeffkreeftmeijer** [comment]
Hey @FrnklyN, thanks for your work on the app icon. Could you post a screenshot of how the icon would look with all layers combined? Also, could you invert the logo and background colors so we can see how it looks with an orange background and a white logo? 

I've created #10 as a separate issue to discuss the top shelf image, so we can close this when the app icon is done.

**Comment by rmens** [comment]
+1 for orange background and white logo. Most tvOS-apps have an icon that is completely filled, without white background. Apple uses this too for most of their icons and third party apps do. Some examples:

![screen shot 2015-11-09 at 17 18 00](https://cloud.githubusercontent.com/assets/6742496/11039074/40966ec8-8706-11e5-9540-0832e5955a2e.png)

**Comment by crxdelsol** [comment]
Ik heb ook een AppIcon gemaakt:

Plaatje 1:
https://www.dropbox.com/s/pmkelgmavdps4c0/0.png?dl=0

Plaatje 2:
https://www.dropbox.com/s/f91rk7gtss9eq9n/1.png?dl=0

Plaatje 3:
https://www.dropbox.com/s/fxevvtzc022wz1k/2.png?dl=0

Plaatje 4:
https://www.dropbox.com/s/gkvxzoyfzoyq3v3/3.png?dl=0

Preview video:
https://www.dropbox.com/s/fw1bdjp62f5x5ud/AppIcon.mov?dl=0

**Comment by jeffkreeftmeijer** [comment]
Hey @FrnklyN and @crxdelsol, thanks for your help!

I like some parts of both of your icons. I think @FrnklyN's size is a little better, but I like the white-on-orange in @crxdelsol's. Could one of you create a new version? I'm expecting @FrnklyN's would need the least amount of changes, so it's probably easier to use that one. _Please post a comment here before you start working on this, so we don't have two people working on the same thing._

Also, I found in the [HIG](https://developer.apple.com/tvos/human-interface-guidelines/icons-and-images/) that we need both a big version (1280px × 768px) and a small one (400px × 240px). We're not submitting the app to the App Store, but let's add it anyway while we're at it. 

Then, could you fork the project, add your icon to the XCode project, and send a pull request? If you get stuck somewhere, just let me know and I'll do my best to help out.

Thanks again for your work so far!

**Comment by crxdelsol** [comment]
I could work on it. It's being designed layered in a vector application. I can change it easily. Just let me know what you want to change. A slight hard shadow behind the white rectangle? Which appears when you move the tile a bit. Rectangle a bit larger. Just let me know.

**Comment by crxdelsol** [comment]
Also since this is vector based, I van easily scale it to the larger version. Already have a template for it, 'cause I need it for my own projects too.

**Comment by jordibruin** [comment]
Hi guys, didn't see this thread before I made my own version. Let me know if you guys like it or if you're going with the orange only one.

https://www.dropbox.com/s/62lz1yi7vs7yfy6/UG-Icon.mov?dl=0

@jeffkreeftmeijer thanks for the app!

**Comment by crxdelsol** [comment]
@jordibruin

That's also a nice one. You could add the numbers to a separate layer, but don't know what the effect would be. But I think personally the colors are a little too much, but dont know what others think. I like to keep it more simpel.

**Comment by jordibruin** [comment]
@crxdelsol I get what you mean. I wanted some more color on my homescreen haha! Good idea about the numbers on a separate layer, let me try it.

**Comment by jeffkreeftmeijer** [comment]
@jordibruin although I love that one, I think it would be nice to keep the icon as simple as possible. Let's go with the white rectangles.

**Comment by jordibruin** [comment]
@jeffkreeftmeijer sure thing. @crxdelsol work your magic!

**Comment by jeffkreeftmeijer** [comment]
@crxdelsol awesome, thanks for offering to pick this up. Could you make the UitzendingGemist icon a little smaller (like @FrnklyN's first version)? That'd make it perfect. Then, could you fork the project and send a pull request like I explained (https://github.com/jeffkreeftmeijer/UitzendingGemist/issues/5#issuecomment-155176283)?

**Comment by crxdelsol** [comment]
I will do this later this evening, and will put it in a pull request with both images.

**Comment by crxdelsol** [comment]
Pull request - requested:

https://github.com/jeffkreeftmeijer/UitzendingGemist/pull/13

**Comment by matthijst** [comment]
@jordibruin could you share the png files for your version? I like how it shows the channel numbers.

**Comment by jordibruin** [comment]
@matthijst I can send you the .sketch file if you can work with that?
