### ISSUE TITLE
Date indicator

### ISSUE THREAD

**Issue by basvroegop** [jeffkreeftmeijer/UitzendingGemist#7]
Would be nice having the date an episode got added mentioned. Right now it only shows the Episode number.

**Comment by jeffkreeftmeijer** [comment]
The Uitzending Gemist API does return `broadcasted_at` timestamps (http://apps-api.uitzendinggemist.nl/episodes/popular.json), but these should be translated into something human readable in the app.

**Comment by BasThomas** [comment]
You could just use `NSDate(timeIntervalSince1970:)` for that (and it should, obviously, be localized).

**Comment by iAmRenzo** [comment]
Would be very nice indeed. For shows like DWDD and Journaal it's hard to see when you've got the latest edition.
Shows like Penoza have episode numbers but I can imagen that a original airdate could come in handy.
But I would argue that the airdate should not only be present in the episode information windows but also on the icons in this screenshot "Meer Penoza", so you can quickly go to the date you search for.
![episode](https://cloud.githubusercontent.com/assets/1183790/11115682/a292e33a-892d-11e5-8a13-2f14aebb4b73.png)

**Comment by jeffkreeftmeijer** [comment]
This would be a great addition. I think it should be added in three places:

- The subtitle on the episode view
- In subtitles under the "more" thumbs
- Behind the episode name in the subtitle in the index views (new and recent)

To make it simple, let's use a date format like this;

    broadcasted_at = 1446838200 // from the API
    date = new Date(broadcasted_at * 1000)
    date.getDate() + "/" + date.getMonth() + "/" + date.getFullYear() + " " + date.getHours() + ":" + date.getMinutes()
