### ISSUE TITLE
Official NPO apps have livestreams for NPO 1, NPO 2 and NPO 3

### ISSUE THREAD

**Issue by basvroegop** [jeffkreeftmeijer/UitzendingGemist#9]
Would be cool to have them in here. Not sure how hard that would be though.

**Comment by johanb** [comment]
Should be relatively easy to add. We've implemented them before for Roku here: https://github.com/roonie/roku-npo-nederland1

**Comment by jeffkreeftmeijer** [comment]
This would be a welcome addition, but I don't think I'll get around to implementing it. I'll accept a pull request for this, if somebody else wants to get their hands dirty.

Maybe a showcaseTemplate would be a good fit; https://developer.apple.com/library/prerelease/tvos/documentation/LanguagesUtilities/Conceptual/ATV_Template_Guide/ShowcaseTemplate.html#//apple_ref/doc/uid/TP40015064-CH27-SW1

**Comment by Mauricevb** [comment]
I made an Apple TV app for this: https://github.com/Mauricevb/NPO-Live-Apple-TV-4

**Comment by jeffkreeftmeijer** [comment]
Hey @Mauricevb, awesome work!

@Sjoerdjanssenen, @johanb and @marijnvdwerf have been working on getting live streams into this app in #15, but I think it might be a good idea to move efforts on that to your project. 

That way, we don't have to reinvent the weel (although that would now be easier by looking at your code), and we'd have a separate project and a separate maintainer for the live TV app, which should make development faster (I don't watch live TV, so I wouldn't notice if anything breaks) and maintaining both projects easier. 

Also, I think having these separate makes more sense. I'd even try to make a separate app for each stream, so you can select it directly from the home screen, but that'd probably make it cumbersome to get everything side loaded on devices, so I think this is our best bet for now. 

So, everyone, what do you think?

**Comment by amphorainteractive** [comment]
I wouldn't want a separate app for each channel. Especially not before apple TV gets folders. I would like the ability to switch channels while watching another channel without needing to go back to the menu (swiping left / right for example) 
But it does make sense to have separate app for live and gemist.
